routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarterasController;
use App\Http\Controllers\CarteraFechasController;
use App\Http\Controllers\DiasController;
use App\Http\Controllers\FuentesController;
use App\Http\Controllers\MovimientosController;
use App\Http\Controllers\TableroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('bienvenido');
});


Route::get('/tablero', [TableroController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::get('/fuentes-de-ingresos', [FuentesController::class, 'index'])->middleware(['auth'])->name('fuentes');
Route::get('/fuentes-de-ingresos/nueva', [FuentesController::class, 'nueva'])->middleware(['auth'])->name('nuevafuente');
Route::get('/fuentes-de-ingresos/{id}/editar', [FuentesController::class, 'editar'])->middleware(['auth'])->name('editarfuente');
Route::post('/fuentes-de-ingresos/guardar', [FuentesController::class, 'guardar'])->middleware(['auth'])->name('guardarfuente');
Route::delete('/fuentes-de-ingresos/{id}', [FuentesController::class, 'eliminar'])->middleware(['auth'])->name('eliminarfuente');
Route::get('/fuentes-de-ingresos/{id}/movimientos', [FuentesController::class, 'movimientos'])->middleware(['auth'])->name('movimientosfuente');

Route::get('/carteras', [CarterasController::class, 'index'])->middleware(['auth'])->name('carteras');
Route::get('/carteras/nueva', [CarterasController::class, 'nueva'])->middleware(['auth'])->name('nuevacartera');
Route::get('/carteras/{id}/editar', [CarterasController::class, 'editar'])->middleware(['auth'])->name('editarcartera');
Route::post('/carteras/guardar', [CarterasController::class, 'guardar'])->middleware(['auth'])->name('guardarcartera');
Route::delete('/carteras/{id}', [CarterasController::class, 'eliminar'])->middleware(['auth'])->name('eliminarcartera');
Route::get('/carteras/{id}/movimientos', [CarterasController::class, 'movimientos'])->middleware(['auth'])->name('movimientoscartera');
Route::get('/carteras/{id}/actualizar', [CarterasController::class, 'actualizar'])->middleware(['auth'])->name('actualizarcantidadcartera');

Route::post('/cartera-fechas/guardar', [CarteraFechasController::class, 'guardar'])->middleware(['auth'])->name('guardarcarterafecha');

Route::get('/dia', [DiasController::class, 'index'])->middleware(['auth'])->name('dia');

Route::get('/movimientos/nuevo', [MovimientosController::class, 'nuevo'])->middleware(['auth'])->name('nuevomovimiento');
Route::get('/movimientos/{id}/editar', [MovimientosController::class, 'editar'])->middleware(['auth'])->name('editarmovimiento');
Route::post('/movimientos/guardar', [MovimientosController::class, 'guardar'])->middleware(['auth'])->name('guardarmovimiento');
Route::delete('/movimientos/{id}', [MovimientosController::class, 'eliminar'])->middleware(['auth'])->name('eliminarmovimiento');

require __DIR__.'/auth.php';

app/Models/Movimiento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Auth;

class Movimiento extends Model
{
    use HasFactory;
    public $timestamps = false;

    public function asignar($datos){
        if($datos['ts']) $this->fecha = date('Y-m-d', $datos['ts']).' '.($datos['hora'] ?? date('H:i:s'));
        $this->tipo = $datos['tipo'];
        $this->user_id = Auth::user()->id;
        $this->fuente_id = $datos['fuente_id'];
        $this->cartera_id = $datos['cartera_id'];
        if($this->tipo == 'A'){            
            $this->cantidad = $datos['cantidad'] - $this->cartera->cantidad['moneda'];
        } else {
            $this->cantidad = $datos['cantidad'];
        }
        $this->descripcion = $datos['descripcion'];
        $this->cantidad_euros = $this->cartera->objetoMoneda->enEuros($this->cantidad);
    }

    public function cartera() {
        return $this->belongsTo(Cartera::class)->withDefault();
    }

    public function getAnoAttribute(){
        $f = new \DateTime($this->fecha);
        return $f->format('Y');
    }

    public function getDiaAttribute(){
        $f = new \DateTime($this->fecha);
        return $f->format('d');
    }

    public function getFechaFormateadaAttribute(){
        $f = new \DateTime($this->fecha);
        return $f->format('d/m/Y H:i:s');
    }

    public function getHoraAttribute(){
        $f = new \DateTime($this->fecha);
        return $f->format('H:i:s');
    }

    public function getMesAttribute(){
        $f = new \DateTime($this->fecha);
        return $f->format('m');
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/InvitadoLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class InvitadoLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.invitado');
    }
}

resources/views/bienvenido.blade.php
<x-invitado-layout>
    <div class="container mx-auto h-full flex flex-1 justify-center items-center">
        <div class="w-full max-w-screen-lg">
            <div class="leading-loose m-4 px-10 pt-5 pb-10 bg-white rounded shadow-xl">
                <div class="text-right">
                    <a href="{{ route('dashboard') }}" class="text-sm text-gray-700 underline">Acceso</a>
                    <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 underline">Registro</a>
                </div>
                <div>
                    <div class="bg-indigo-400 rounded p-7 text-white mb-3">
                        <h2 class="font-bold text-lg mb-2">¡Bienvenido a Gestionam.ehhh.es!</h2>
                        <p>Somos una aplicación para organizar tu economía. Ofrecemos una forma divertiva de llevar tu economía personal,
                            controlando tus gastos e ingresos y tratando de adivinar los gastos e ingresos futuros. </p>
                        <p>Pero esto ya lo puedes encontrar en cualquier aplicación bancaria o cientos de aplicaciones gratuitas. ¿Por qué
                            utilizar nuestra aplicación? A continuación te mostramos nuestras principales ventajas. Esperamos convencerte.</p>
                    </div>
                    <div class="p-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Multi-cuenta</div>
                                <p class="text-center text-indigo-400 text-5xl">
                                    <i class="fas fa-piggy-bank" aria-hidden="true"></i>
                                </p>
                                <p>Mantén los datos de todas las cuentas que tengas. Contabiliza el dinero que tienes en tu monedero o en
                                la hucha.</p>
                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Multi-origen</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fas fa-store-alt" aria-hidden="true"></i></p>
                                <p>Puedes mantener los datos de todas las fuentes de ingresos y gastos, y consultar todo el dinero que llevas
                                gastado o ganado de cada uno de ellos.</p>
                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Multi-moneda</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fab fa-bitcoin" aria-hidden="true"></i></p>
                                <p>Cada cuenta o cartera puede estar asociado a una moneda. Podrás mantener tu cuenta del banco en euros y tu
                                wallet en bitcoins.</p>
                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Predictivo</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fas fa-meh-rolling-eyes" aria-hidden="true"></i></p>
                                <p>Adivina los gastos e ingresos que están por venir y calcula cuando podrás comprar ese capricho que tienes en mente.</p>
                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Te escuchamos</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fas fa-comment-dots" aria-hidden="true"></i></p>
                                <p>Queremos que la aplicación sea útil para todo el mundo. Si tienes alguna idea, no dudes en <a href="mail_to:leroj7@gmail.com">escribirnos</a>.</p>                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Anónimo</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fas fa-user-secret" aria-hidden="true"></i></p>
                                <p>No queremos ningún dato personal tuyo, sólo un nombre de usuario.</p>
                            </div>
                        </div>
                        <div class="max-w-sm rounded overflow-hidden shadow-lg">
                            <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">Gratuito</div>
                                <p class="text-center text-indigo-400 text-5xl"><i class="fab fa-creative-commons-zero" aria-hidden="true"></i></p>
                                <p>No te cobraremos por la aplicación, ni ahora ni NUNCA. Como mucho aspiramos a conseguir meter algo de publicidad para recuperar el esfuerzo empleado.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-invitado-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/tablero.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight mb-3">
                ¡ Hola ! Según nuestros datos dispones de {{$total}} &euro;.
            </h2>
            <ion-content class="bg-white overflow-hidden shadow-xl sm:rounded-lg slider-carteras">
                <ion-slides pager="true" slidesPerView=3 freeMode="true" class="mt-2">
                    @foreach ($carteras as $cartera)
                        <ion-slide>
                            <div class="cartera shadow-lg bg-{{$colores[$loop->index%7]}}-400 border-l-8 hover:bg-$colores[$loop->index%7]-600 border-$colores[$loop->index%7]-600 mb-2 p-2 w-full mx-2">
                                <div class="p-4 flex flex-col">
                                    <a href="#" class="no-underline text-white text-2xl">
                                        {{$cartera['cantidad']}} &euro;
                                    </a>
                                    <a href="#" class="no-underline text-white text-lg">
                                        {{$cartera['nombre']}}
                                    </a>
                                </div>
                            </div>
                        </ion-slide>
                    @endforeach
                </ion-slides>
            </ion-content>
            <!-- Calendario -->
            <div class="container mx-auto py-2 md:py-24">
                <div class="bg-white rounded-lg shadow-xl overflow-hidden">
                    <div class="flex items-center justify-between py-2 px-6">
                        <div>
                            <span class="text-lg font-bold text-gray-800">{{$calendario->nombreMes()}}</span>
                            <span x-text="ano" class="ml-1 text-lg text-gray-600 font-normal">{{$calendario->ano}}</span>
                        </div>
                        <div class="border rounded-lg px-1" style="padding-top: 2px;">
                            <a href="/tablero?m={{$calendario->mesAnterior()}}&a={{$calendario->anoAnterior()}}">
                                <button 
                                    type="button"
                                    class="leading-none rounded-lg transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 items-center" 
                                >
                                    <svg class="h-6 w-6 text-gray-500 inline-flex leading-none"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
                                    </svg>  
                                </button>
                            </a>
                            <div class="border-r inline-flex h-6"></div>		
                            <a href="/tablero?m={{$calendario->mesSiguiente()}}&a={{$calendario->anoSiguiente()}}">
                                <button 
                                    type="button"
                                    class="leading-none rounded-lg transition ease-in-out duration-100 inline-flex items-center cursor-pointer hover:bg-gray-200 p-1" 
                                >
                                    <svg class="h-6 w-6 text-gray-500 inline-flex leading-none"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                    </svg>									  
                                </button>
                            </a>
                        </div>
                    </div>	
                    <div class="-mx-1 -mb-1">
                        <div class="flex flex-wrap border-t border-l">
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">L</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">M</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">X</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">J</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">V</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">S</div>
                            <div style="width: 14.28%;" class="text-center border-r border-b px-4 pt-2 text-white bg-indigo-400">D</div>
                            @for ($i = 0; $i < $calendario->huecos(); $i++)
                                <div 
                                    style="width: 14.28%; height: 120px"
                                    class="text-center border-r border-b px-4 pt-2"	
                                ></div>
                            @endfor
                            @foreach ($calendario->dias() as $dia)
                                <div style="width: 14.28%; height: 120px" class="px-4 pt-2 border-r border-b relative">
                                    <div>
                                        <a 
                                            href="{{ route( 'dia', ['m' => $calendario->mes, 'd' => $dia['dia'], 'a' => $calendario->ano]) }}"
                                            class="inline-flex w-6 h-6 items-center justify-center cursor-pointer text-center leading-none rounded-full transition ease-in-out duration-100 text-gray-700 hover:bg-blue-200"	
                                        >
                                            {{$dia['dia']}}
                                        </a>
                                    </div>
                                    <div style="height: 80px;" class="overflow-y-auto mt-1">
                                        @foreach ($dia['movimientos'] as $movimiento)
                                            @if ($movimiento->tipo == "I")
                                                <div title="{{$movimiento->descripcion}}"
                                                    class="px-2 py-1 rounded-lg mt-1 overflow-hidden border border-green-200 text-green-800 bg-green-100">
                                                    <p class="text-sm truncate leading-tight">
                                                        {{$movimiento->descripcion}}
                                                    </p>
                                                </div>
                                            @else
                                                @if ($movimiento->tipo == "A")
                                                    <div title="{{$movimiento->descripcion}}"
                                                        class="px-2 py-1 rounded-lg mt-1 overflow-hidden border border-indigo-200 text-indigo-800 bg-indigo-100">
                                                        <p class="text-sm truncate leading-tight">
                                                            {{$movimiento->descripcion}}
                                                        </p>
                                                    </div>
                                                @else
                                                    <div title="{{$movimiento->descripcion}}"
                                                        class="px-2 py-1 rounded-lg mt-1 overflow-hidden border border-red-200 text-red-800 bg-red-100">
                                                        <p class="text-sm truncate leading-tight">
                                                            {{$movimiento->descripcion}}
                                                        </p>
                                                    </div>
                                                @endif
                                            @endif
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var slides = document.querySelector('ion-slides');
        slides.options = { slidesPerView: 3 };
    </script>
</x-app-layout>